In [9]:

import numpy as np
a=np.array(["Ram","Ravi","Suraj","Ankur"])
print(a[1],a[3])

Ravi Ankur


In [11]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[[1,3]])

[20 40]


In [17]:
Arr=np.array([10,20,30,40,50])
print(Arr[Arr>25])


[30 40 50]


In [18]:
marks=np.array([23,45,67,89,99])
print(marks[marks>35])

[45 67 89 99]


In [21]:
marks=np.array([11,23,45,41,19])
print(marks[marks>20])

[23 45 41]


In [25]:
arr=np.array([23,45,67,89,98])
for i in range(1,5):
     print(arr[i])

45
67
89
98


In [30]:
for i in [10,20,30,440,]:
    print(i)

10
20
30
440


In [33]:
arr=np.array([10,20,30,40,60,])
for i in arr:
    print(i)

10
20
30
40
60


In [45]:
ar=np.array([[1,3,7,8,9],[4,5,8,7,2]])
for i in ar:
    print(i)


[1 3 7 8 9]
[4 5 8 7 2]


In [41]:
mar=np.array([[20,30],[45,78,],[56,89]])
for i in mar:
    print(i)

[20 30]
[45 78]
[56 89]


In [48]:
import numpy as np
arr=np.array ([10,20,30,50,89,78,78,])
for i in np.nditer(arr):
      print(i)

10
20
30
50
89
78
78


In [51]:
a=np.array(["swathi"])
b=np.array(["chigurla"])
print(a+" "+b)

['swathi chigurla']


In [69]:
a=np.array([12,3,4,6])
b=np.array([3,5,7,8])
print(a,b)

[12  3  4  6] [3 5 7 8]


In [70]:
arr=np.array([10,20,30,40])
print(arr[2])

30


In [73]:
arr=np.array([10,20,30,40,30,50])
x=np.where(arr==30)
print(x)

(array([2, 4]),)


In [75]:
arr=np.array([10,20,30,40])
result=sorted(arr)
print(result)

[np.int64(10), np.int64(20), np.int64(30), np.int64(40)]


In [77]:
a=np.array([10,30,20])
b=np.array([40,50,60])
c=np.concatenate([a,b])
print(c)

[10 30 20 40 50 60]


In [78]:
arr=np.array([20,4,5,6,8])
x=np.sort(arr)
print(x)

[ 4  5  6  8 20]


In [90]:
a=np.array([10,20,20])
b=np.array([40,50,60])
print(a+b)

[50 70 80]


In [94]:
marks=np.array([40,35,60,80,75])
print(marks[marks>=45])

[60 80 75]


In [102]:
a=np.array([11,33,55,66,99])
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.mean(a))

264
99
11
52.8


In [103]:
a=np.array([5,6])
x=np.square(a*a)
print(x)

[ 625 1296]


In [104]:
print(np.power(arr,2))

[400  16  25  36  64]
